apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: thingpark-csi-gp2-xfs
parameters:
  fsType: xfs
  type: gp2
provisioner: ebs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: thingpark-csi-gp2-ext4
parameters:
  fsType: ext4
  type: gp2
provisioner: ebs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
