apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: thingpark-csi-standard-lrs-xfs
parameters:
  fsType: xfs
  skuName: StandardSSD_LRS
provisioner: disk.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: thingpark-csi-premium-lrs-xfs
parameters:
  fsType: xfs
  skuName: Premium_LRS
provisioner: disk.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: thingpark-csi-premium-lrs-ext4
parameters:
  fsType: ext4
  skuName: Premium_LRS
provisioner: disk.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
